name: CI
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  rubocop:
    name: "Rubocop"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "ruby"
          bundler-cache: true
      - run: bundle exec rubocop
  test:
    name: "Test / Ruby ${{ matrix.ruby }} / Rails ${{ matrix.rails }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rails: ["7.2", "8.0", "main"]
        ruby: ["3.2", "3.3", "3.4", "head"]
        exclude:
          - rails: "8.0"
            ruby: "3.1"
          - rails: main
            ruby: "3.1"
    env:
      BUNDLE_GEMFILE: gemfiles/rails_${{ matrix.rails }}.gemfile
    steps:
      - uses: actions/checkout@v5
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: bundle exec rake test
  test-all:
    name: "Test / All"
    runs-on: ubuntu-latest
    needs: [test]
    if: always()
    steps:
      - name: All tests ok
        if: ${{ !(contains(needs.*.result, 'failure')) }}
        run: exit 0
      - name: Some tests failed
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1
